displayName: MaxMind GeoIP with Coordinates Redux

summary: 'Getting data from MaxMind GeoIP databases and pass it downstream via HTTP request headers.'

type: middleware

import: github.com/cmmoran/traefik_geoip

testData:
  dbPath: 'geoLite2-country.mmdb'
  debug: false
  excludeIPs:
    - "192.168.0.0/16"
    - "172.16.0.0/12"
    - "10.0.0.0/8"
    - "127.0.0.1/8"
  setRealIP: true
